content = (
    "import React, { useState } from 'react';\n"
    "import { useAppState } from '../../core/database/AppStateContext';\n"
    "import { Building2, MapPin, Calendar, TrendingUp, Users, FileText, CheckCircle2, AlertTriangle, Clock, DollarSign, BarChart3 } from 'lucide-react';\n"
    "\n"
    "export const VueProjet360: React.FC = () => {\n"
    "  const { projects } = useAppState();\n"
    "  const [selectedId, setSelectedId] = useState<string | null>(null);\n"
    "  const selected = projects.find(p => p.id === selectedId) ?? projects[0] ?? null;\n"
    "\n"
    "  const phases = [\n"
    "    { label: 'Installation & Base vie', pct: 100, color: 'bg-emerald-500' },\n"
    "    { label: 'Fondations', pct: 100, color: 'bg-emerald-500' },\n"
    "    { label: 'Superstructure Beton Arme', pct: 67, color: 'bg-amber-400' },\n"
    "    { label: 'Charpente Metallique', pct: 20, color: 'bg-blue-400' },\n"
    "    { label: 'Second Oeuvre', pct: 0, color: 'bg-slate-200' },\n"
    "    { label: 'Finitions & Reception', pct: 0, color: 'bg-slate-200' },\n"
    "  ];\n"
    "\n"
    "  const kpis = [\n"
    "    { icon: TrendingUp, label: 'Avancement Global', value: '63%', sub: 'Sur objectif planifie', col: 'text-emerald-600 bg-emerald-50 border-emerald-200' },\n"
    "    { icon: DollarSign, label: 'Budget Consomme', value: '58%', sub: '696 000 000 FCFA', col: 'text-blue-600 bg-blue-50 border-blue-200' },\n"
    "    { icon: Clock, label: 'Delai Restant', value: '147 j', sub: 'Livraison prev. 15/01/2026', col: 'text-amber-600 bg-amber-50 border-amber-200' },\n"
    "    { icon: AlertTriangle, label: 'Alertes Actives', value: '2', sub: '1 critique, 1 elevee', col: 'text-red-600 bg-red-50 border-red-200' },\n"
    "  ];\n"
    "\n"
    "  const team = [\n"
    "    { role: 'Directeur de Projet', name: 'Koffi Serge Kouassi', avatar: 'KS' },\n"
    "    { role: 'Conducteur de Travaux', name: 'Yao Jean-Marc Konan', avatar: 'YJ' },\n"
    "    { role: 'Chef de Chantier', name: 'Bakayoko Lassina', avatar: 'BL' },\n"
    "    { role: 'Responsable QSE', name: 'Coulibaly Mariam', avatar: 'CM' },\n"
    "  ];\n"
    "\n"
    "  const recentDocs = [\n"
    "    { name: 'PV_Reunion_Chantier_S33.pdf', date: '18/08/2025', type: 'PDF' },\n"
    "    { name: 'Planning_Actualise_Aout.xlsx', date: '15/08/2025', type: 'XLS' },\n"
    "    { name: 'Rapport_Journalier_19_08.pdf', date: '19/08/2025', type: 'PDF' },\n"
    "  ];\n"
    "\n"
    "  return (\n"
    "    <div className=\"space-y-6 text-xs\">\n"
    "\n"
    "      {/* Selecteur de projet */}\n"
    "      <div className=\"bg-white rounded-2xl border border-slate-200 shadow-sm p-4 flex flex-wrap items-center gap-3\">\n"
    "        <span className=\"font-bold text-slate-600 text-[11px] uppercase tracking-wide\">Projet :</span>\n"
    "        <select value={selectedId ?? projects[0]?.id ?? ''} onChange={e => setSelectedId(e.target.value)} className=\"border border-slate-200 rounded-lg px-3 py-1.5 text-xs font-semibold text-slate-800 bg-white focus:outline-none\">\n"
    "          {projects.map(p => (<option key={p.id} value={p.id}>{p.name}</option>))}\n"
    "        </select>\n"
    "        <span className=\"ml-auto text-[10px] text-slate-400\">Vue 360 deg consolidee</span>\n"
    "      </div>\n"
    "\n"
    "      {/* Header Projet */}\n"
    "      {selected && (\n"
    "        <div className=\"bg-slate-900 text-white rounded-2xl p-6 shadow-xl flex flex-wrap items-start justify-between gap-4\">\n"
    "          <div>\n"
    "            <div className=\"flex items-center gap-2 mb-1\">\n"
    "              <Building2 size={18} className=\"text-blue-400\" />\n"
    "              <span className=\"text-[10px] font-bold text-blue-400 uppercase tracking-widest\">Vue Projet 360 deg</span>\n"
    "            </div>\n"
    "            <h1 className=\"text-xl font-extrabold tracking-tight\">{selected.name}</h1>\n"
    "            <div className=\"flex flex-wrap items-center gap-4 mt-2 text-slate-400 text-[11px]\">\n"
    "              <span className=\"flex items-center gap-1\"><MapPin size={12} /> Cote d&apos;Ivoire</span>\n"
    "              <span className=\"flex items-center gap-1\"><Calendar size={12} /> Demarrage : 01/03/2025</span>\n"
    "              <span className=\"flex items-center gap-1\"><Calendar size={12} /> Livraison : 15/01/2026</span>\n"
    "            </div>\n"
    "          </div>\n"
    "          <span className=\"bg-amber-500 text-white text-[10px] font-extrabold px-3 py-1 rounded-full uppercase\">En cours</span>\n"
    "        </div>\n"
    "      )}\n"
    "\n"
    "      {/* KPI Row */}\n"
    "      <div className=\"grid grid-cols-2 xl:grid-cols-4 gap-4\">\n"
    "        {kpis.map((kpi, i) => { const Icon = kpi.icon; return (\n"
    "          <div key={i} className={'rounded-xl border p-4 space-y-1 shadow-sm ' + kpi.col}>\n"
    "            <Icon size={18} />\n"
    "            <div className=\"font-extrabold text-slate-900 text-lg leading-none\">{kpi.value}</div>\n"
    "            <div className=\"font-bold text-[11px] uppercase tracking-wide\">{kpi.label}</div>\n"
    "            <div className=\"text-[10px] text-slate-500\">{kpi.sub}</div>\n"
    "          </div>\n"
    "        ); })}\n"
    "      </div>\n"
    "\n"
    "      {/* Avancement + Equipe */}\n"
    "      <div className=\"grid grid-cols-1 xl:grid-cols-3 gap-5\">\n"
    "        <div className=\"xl:col-span-2 bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden\">\n"
    "          <div className=\"p-4 border-b border-slate-100 flex items-center gap-2\"><BarChart3 size={15} className=\"text-blue-500\" /><h2 className=\"font-extrabold text-slate-800\">Avancement par Phase de Travaux</h2></div>\n"
    "          <div className=\"p-5 space-y-4\">\n"
    "            {phases.map((ph, i) => (\n"
    "              <div key={i} className=\"space-y-1\">\n"
    "                <div className=\"flex justify-between text-[11px] font-semibold text-slate-700\"><span>{ph.label}</span><span className=\"font-bold\">{ph.pct}%</span></div>\n"
    "                <div className=\"w-full bg-slate-100 rounded-full h-2\"><div className={'h-2 rounded-full transition-all duration-500 ' + ph.color} style={{ width: ph.pct + '%' }} /></div>\n"
    "              </div>\n"
    "            ))}\n"
    "          </div>\n"
    "        </div>\n"
    "        <div className=\"bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden\">\n"
    "          <div className=\"p-4 border-b border-slate-100 flex items-center gap-2\"><Users size={15} className=\"text-indigo-500\" /><h2 className=\"font-extrabold text-slate-800\">Equipe Projet</h2></div>\n"
    "          <div className=\"divide-y divide-slate-50\">\n"
    "            {team.map((m, i) => (\n"
    "              <div key={i} className=\"p-4 flex items-center gap-3\">\n"
    "                <div className=\"w-9 h-9 rounded-full bg-blue-600 text-white font-extrabold text-xs flex items-center justify-center flex-shrink-0\">{m.avatar}</div>\n"
    "                <div><div className=\"font-bold text-slate-800\">{m.name}</div><div className=\"text-[10px] text-slate-500\">{m.role}</div></div>\n"
    "                <CheckCircle2 size={14} className=\"ml-auto text-emerald-500\" />\n"
    "              </div>\n"
    "            ))}\n"
    "          </div>\n"
    "        </div>\n"
    "      </div>\n"
    "\n"
    "      {/* Documents recents */}\n"
    "      <div className=\"bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden\">\n"
    "        <div className=\"p-4 border-b border-slate-100 flex items-center gap-2\"><FileText size={15} className=\"text-slate-500\" /><h2 className=\"font-extrabold text-slate-800\">Documents Recents</h2></div>\n"
    "        <div className=\"divide-y divide-slate-50\">\n"
    "          {recentDocs.map((doc, i) => (\n"
    "            <div key={i} className=\"px-5 py-3 flex items-center justify-between hover:bg-slate-50 transition\">\n"
    "              <div className=\"flex items-center gap-3\">\n"
    "                <span className={'text-[10px] font-extrabold px-2 py-0.5 rounded ' + (doc.type === 'PDF' ? 'bg-red-100 text-red-700' : 'bg-emerald-100 text-emerald-700')}>{doc.type}</span>\n"
    "                <span className=\"font-semibold text-slate-700\">{doc.name}</span>\n"
    "              </div>\n"
    "              <span className=\"text-[10px] text-slate-400\">{doc.date}</span>\n"
    "            </div>\n"
    "          ))}\n"
    "        </div>\n"
    "      </div>\n"
    "\n"
    "    </div>\n"
    "  );\n"
    "};\n"
)

with open('src/modules/projects/VueProjet360.tsx', 'w', encoding='utf-8') as f:
    f.write(content)
print('OK')
