import {
  Project,
  WBSNode,
  PurchaseRequest,
  PurchaseOrder,
  GoodsReceipt,
  StockItem,
  StockMovement,
  DailyReport,
  SystemAlert,
  AuditLog,
  BudgetVersion
} from '../types';

import { REAL_EXCEL_PROJECTS, REAL_EXCEL_WBS, REAL_EXCEL_PRODUCTION } from '../../data/realExcelData';

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'CIV-2026-ASS-SON-001',
    code: 'CIV-2026-ASS-SON-001',
    domainCode: 'ASS',
    name: 'Station de traitement des boues de vidange de la ville Abidjan Ouest (Songon)',
    company: 'GEBAT SA',
    client: 'Ministère de l’Hydraulique & Assainissement / ONEP',
    country: 'Côte d’Ivoire',
    location: 'Songon, Abidjan Ouest',
    activity: 'Station de Traitement des Boues',
    manager: 'SEA Alphonse',
    contractRef: 'CTR-GEBAT-2026-ASS-SON-001',
    contractAmount: 1412416250,
    currency: 'XOF',
    signatureDate: '2026-01-15',
    startDate: '2026-07-01',
    durationMonths: 6,
    endDate: '2027-01-31',
    initialBudget: 778028406,
    revisedBudget: 778028406,
    progress: 3.10,
    status: 'En cours',
    risk: 'Modéré'
  },
  {
    id: 'CIV-2026-ASS-BEN-002',
    code: 'CIV-2026-ASS-BEN-002',
    domainCode: 'ASS',
    name: 'Station de traitement des boues de vidange de la ville Abidjan Est commune de Bingerville',
    company: 'GEBAT SA',
    client: 'Ministère de l’Hydraulique & Assainissement / ONEP',
    country: 'Côte d’Ivoire',
    location: 'Bingerville, Abidjan Est',
    activity: 'Station de Traitement des Boues',
    manager: 'KOUASSI Jean',
    contractRef: 'CTR-GEBAT-2026-ASS-BEN-002',
    contractAmount: 3428000000,
    currency: 'XOF',
    signatureDate: '2026-01-15',
    startDate: '2026-06-01',
    durationMonths: 15,
    endDate: '2027-09-01',
    initialBudget: 1890812405,
    revisedBudget: 1890812405,
    progress: 13.02,
    status: 'En cours',
    risk: 'Faible'
  }
];

export const INITIAL_WBS: Record<string, WBSNode[]> = {
  'CIV-2026-ASS-001': [
    {
      id: 'CIV-2026-ASS-001-03',
      projectId: 'CIV-2026-ASS-001',
      code: 'CIV-2026-ASS-001 / 03',
      name: '03 — Travaux de Génie Civil',
      initialBudget: 625000000,
      revisedBudget: 625000000,
      committed: 480000000,
      actualCost: 310000000,
      forecast: 388000000,
      eac: 698000000,
      progress: 45,
      nature: 'LOT',
      manager: 'SEA Alphonse',
      children: [
        {
          id: 'CIV-2026-ASS-001-03-02',
          projectId: 'CIV-2026-ASS-001',
          code: 'CIV-2026-ASS-001 / 03 / 02',
          name: '02 — Structure Béton Armé',
          initialBudget: 350000000,
          revisedBudget: 350000000,
          committed: 280000000,
          actualCost: 195000000,
          forecast: 200000000,
          eac: 395000000,
          progress: 50,
          nature: 'LOT',
          manager: 'SEA Alphonse',
          children: [
            {
              id: 'CIV-2026-ASS-001-03-02-004',
              projectId: 'CIV-2026-ASS-001',
              code: 'CIV-2026-ASS-001 / 03 / 02 / 004',
              name: '004 — Réalisation béton armé radier & voiles',
              unit: 'm3',
              plannedQty: 450,
              unitCost: 110000,
              initialBudget: 49500000,
              revisedBudget: 49000000,
              committed: 49000000,
              actualCost: 32000000,
              forecast: 25000000,
              eac: 57000000,
              progress: 60,
              nature: 'MAT',
              manager: 'SEA Alphonse'
            }
          ]
        }
      ]
    }
  ],
  ...REAL_EXCEL_WBS,
};

export const INITIAL_STOCK_ITEMS: StockItem[] = [
  {
    id: 'STK-CIM-CHF',
    code: 'ART-CIM-CHF',
    name: 'CIMENT CHF',
    category: 'Matériaux Liants',
    unit: 'SAC',
    warehouse: 'Base Chantier ONAD Bingerville',
    minThreshold: 50,
    currentStock: 0,
    averageUnitPrice: 5200,
    totalValue: 0,
  },
  {
    id: 'STK-CIM-CPA',
    code: 'ART-CIM-CPA',
    name: 'CIMENT CPA (Coulage de radier et BP)',
    category: 'Matériaux Liants',
    unit: 'SAC',
    warehouse: 'Base Chantier ONAD Bingerville',
    minThreshold: 300,
    currentStock: 585,
    averageUnitPrice: 4900,
    totalValue: 2866500,
  },
  {
    id: 'STK-CIM-CPJ',
    code: 'ART-CIM-CPJ',
    name: 'CIMENT CPJ',
    category: 'Matériaux Liants',
    unit: 'SAC',
    warehouse: 'Base Chantier ONAD Bingerville',
    minThreshold: 200,
    currentStock: 0,
    averageUnitPrice: 4800,
    totalValue: 0,
  },
  {
    id: 'STK-FER-06',
    code: 'ART-FER-06',
    name: 'FER 6 (Barres 12m)',
    category: 'Aciers & Armatures',
    unit: 'BARRE',
    warehouse: 'Base Chantier ONAD Bingerville',
    minThreshold: 100,
    currentStock: 0,
    averageUnitPrice: 1800,
    totalValue: 0,
  },
  {
    id: 'STK-FER-08',
    code: 'ART-FER-08',
    name: 'FER 8 (Chevalier de radier)',
    category: 'Aciers & Armatures',
    unit: 'BARRE',
    warehouse: 'Base Chantier ONAD Bingerville',
    minThreshold: 150,
    currentStock: 227,
    averageUnitPrice: 3100,
    totalValue: 703700,
  },
  {
    id: 'STK-FER-10',
    code: 'ART-FER-10',
    name: 'FER 10 (Ferraillage de radier et Voile)',
    category: 'Aciers & Armatures',
    unit: 'BARRE',
    warehouse: 'Base Chantier ONAD Bingerville',
    minThreshold: 500,
    currentStock: 1037,
    averageUnitPrice: 4800,
    totalValue: 4977600,
  },
  {
    id: 'STK-FER-12',
    code: 'ART-FER-12',
    name: 'FER 12 (Barres 12m)',
    category: 'Aciers & Armatures',
    unit: 'BARRE',
    warehouse: 'Base Chantier ONAD Bingerville',
    minThreshold: 200,
    currentStock: 0,
    averageUnitPrice: 6500,
    totalValue: 0,
  },
  {
    id: 'STK-FER-14',
    code: 'ART-FER-14',
    name: 'FER 14 (Barres 12m)',
    category: 'Aciers & Armatures',
    unit: 'BARRE',
    warehouse: 'Base Chantier ONAD Bingerville',
    minThreshold: 100,
    currentStock: 0,
    averageUnitPrice: 9200,
    totalValue: 0,
  },
  {
    id: 'STK-FER-16',
    code: 'ART-FER-16',
    name: 'FER 16 (Barres 12m)',
    category: 'Aciers & Armatures',
    unit: 'BARRE',
    warehouse: 'Base Chantier ONAD Bingerville',
    minThreshold: 50,
    currentStock: 0,
    averageUnitPrice: 12000,
    totalValue: 0,
  },
  {
    id: 'STK-PNT-08A',
    code: 'ART-PNT-08A',
    name: 'POINTE N°8 (70mm)',
    category: 'Quincaillerie & Fixations',
    unit: 'UNITÉ',
    warehouse: 'Base Chantier ONAD Bingerville',
    minThreshold: 20,
    currentStock: 0,
    averageUnitPrice: 1500,
    totalValue: 0,
  },
  {
    id: 'STK-PNT-08B',
    code: 'ART-PNT-08B',
    name: 'POINTE N°8 (80mm / Coffrage)',
    category: 'Quincaillerie & Fixations',
    unit: 'UNITÉ',
    warehouse: 'Base Chantier ONAD Bingerville',
    minThreshold: 50,
    currentStock: 0,
    averageUnitPrice: 1500,
    totalValue: 0,
  },
  {
    id: 'STK-FIL-ATT',
    code: 'ART-FIL-ATT',
    name: 'FIL D’ATTACHE (Attache de ferraillage)',
    category: 'Quincaillerie & Fixations',
    unit: 'Rouleau',
    warehouse: 'Base Chantier ONAD Bingerville',
    minThreshold: 25,
    currentStock: 75,
    averageUnitPrice: 8500,
    totalValue: 637500,
  },
  {
    id: 'STK-GRAVIER',
    code: 'ART-AGG-GRAV',
    name: 'GRAVIER (Granulats béton 15/25)',
    category: 'Agrégats & Carrière',
    unit: 'Voy',
    warehouse: 'Base Chantier ONAD Bingerville',
    minThreshold: 5,
    currentStock: 7.75,
    averageUnitPrice: 180000,
    totalValue: 1395000,
  },
  {
    id: 'STK-SABLE',
    code: 'ART-AGG-SABL',
    name: 'SABLE (Sable de lagune tamisé)',
    category: 'Agrégats & Carrière',
    unit: 'Voy',
    warehouse: 'Base Chantier ONAD Bingerville',
    minThreshold: 5,
    currentStock: 2.25,
    averageUnitPrice: 140000,
    totalValue: 315000,
  },
  /* BASE CHANTIER ONAD SONGON */
  {
    id: 'STK-SNG-CIM-CHF',
    code: 'ART-SNG-CIM-CHF',
    name: 'CIMENT CHF',
    category: 'Matériaux Liants',
    unit: 'SAC',
    warehouse: 'Base Chantier ONAD Songon',
    minThreshold: 50,
    currentStock: 0,
    averageUnitPrice: 5200,
    totalValue: 0,
  },
  {
    id: 'STK-SNG-CIM-CPA',
    code: 'ART-SNG-CIM-CPA',
    name: 'CIMENT CPA (Coulage de voiles et radiers)',
    category: 'Matériaux Liants',
    unit: 'SAC',
    warehouse: 'Base Chantier ONAD Songon',
    minThreshold: 250,
    currentStock: 410,
    averageUnitPrice: 4900,
    totalValue: 2009000,
  },
  {
    id: 'STK-SNG-CIM-CPJ',
    code: 'ART-SNG-CIM-CPJ',
    name: 'CIMENT CPJ',
    category: 'Matériaux Liants',
    unit: 'SAC',
    warehouse: 'Base Chantier ONAD Songon',
    minThreshold: 150,
    currentStock: 80,
    averageUnitPrice: 4800,
    totalValue: 384000,
  },
  {
    id: 'STK-SNG-FER-06',
    code: 'ART-SNG-FER-06',
    name: 'FER 6 (Barres 12m)',
    category: 'Aciers & Armatures',
    unit: 'BARRE',
    warehouse: 'Base Chantier ONAD Songon',
    minThreshold: 100,
    currentStock: 0,
    averageUnitPrice: 1800,
    totalValue: 0,
  },
  {
    id: 'STK-SNG-FER-08',
    code: 'ART-SNG-FER-08',
    name: 'FER 8 (Chevalier de radier & étriers)',
    category: 'Aciers & Armatures',
    unit: 'BARRE',
    warehouse: 'Base Chantier ONAD Songon',
    minThreshold: 150,
    currentStock: 185,
    averageUnitPrice: 3100,
    totalValue: 573500,
  },
  {
    id: 'STK-SNG-FER-10',
    code: 'ART-SNG-FER-10',
    name: 'FER 10 (Ferraillage de radier et Voiles)',
    category: 'Aciers & Armatures',
    unit: 'BARRE',
    warehouse: 'Base Chantier ONAD Songon',
    minThreshold: 400,
    currentStock: 845,
    averageUnitPrice: 4800,
    totalValue: 4056000,
  },
  {
    id: 'STK-SNG-FER-12',
    code: 'ART-SNG-FER-12',
    name: 'FER 12 (Armatures poteaux & poutres)',
    category: 'Aciers & Armatures',
    unit: 'BARRE',
    warehouse: 'Base Chantier ONAD Songon',
    minThreshold: 200,
    currentStock: 120,
    averageUnitPrice: 6500,
    totalValue: 780000,
  },
  {
    id: 'STK-SNG-FER-14',
    code: 'ART-SNG-FER-14',
    name: 'FER 14 (Barres 12m)',
    category: 'Aciers & Armatures',
    unit: 'BARRE',
    warehouse: 'Base Chantier ONAD Songon',
    minThreshold: 100,
    currentStock: 0,
    averageUnitPrice: 9200,
    totalValue: 0,
  },
  {
    id: 'STK-SNG-FER-16',
    code: 'ART-SNG-FER-16',
    name: 'FER 16 (Barres 12m)',
    category: 'Aciers & Armatures',
    unit: 'BARRE',
    warehouse: 'Base Chantier ONAD Songon',
    minThreshold: 50,
    currentStock: 0,
    averageUnitPrice: 12000,
    totalValue: 0,
  },
  {
    id: 'STK-SNG-PNT-08A',
    code: 'ART-SNG-PNT-08A',
    name: 'POINTE N°8 (70mm)',
    category: 'Quincaillerie & Fixations',
    unit: 'UNITÉ',
    warehouse: 'Base Chantier ONAD Songon',
    minThreshold: 20,
    currentStock: 0,
    averageUnitPrice: 1500,
    totalValue: 0,
  },
  {
    id: 'STK-SNG-PNT-08B',
    code: 'ART-SNG-PNT-08B',
    name: 'POINTE N°8 (80mm / Coffrage)',
    category: 'Quincaillerie & Fixations',
    unit: 'UNITÉ',
    warehouse: 'Base Chantier ONAD Songon',
    minThreshold: 50,
    currentStock: 0,
    averageUnitPrice: 1500,
    totalValue: 0,
  },
  {
    id: 'STK-SNG-FIL-ATT',
    code: 'ART-SNG-FIL-ATT',
    name: 'FIL D’ATTACHE (Attache de ferraillage)',
    category: 'Quincaillerie & Fixations',
    unit: 'Rouleau',
    warehouse: 'Base Chantier ONAD Songon',
    minThreshold: 20,
    currentStock: 52,
    averageUnitPrice: 8500,
    totalValue: 442000,
  },
  {
    id: 'STK-SNG-GRAVIER',
    code: 'ART-SNG-AGG-GRAV',
    name: 'GRAVIER (Granulats béton 15/25)',
    category: 'Agrégats & Carrière',
    unit: 'Voy',
    warehouse: 'Base Chantier ONAD Songon',
    minThreshold: 5,
    currentStock: 5.5,
    averageUnitPrice: 180000,
    totalValue: 990000,
  },
  {
    id: 'STK-SNG-SABLE',
    code: 'ART-SNG-AGG-SABL',
    name: 'SABLE (Sable de lagune tamisé)',
    category: 'Agrégats & Carrière',
    unit: 'Voy',
    warehouse: 'Base Chantier ONAD Songon',
    minThreshold: 5,
    currentStock: 3.5,
    averageUnitPrice: 140000,
    totalValue: 490000,
  },
];

export const INITIAL_WAREHOUSES: Warehouse[] = [
  {
    id: 'MAG-01',
    code: 'MAG-ABJ-01',
    name: 'Magasin Central Abidjan (Yopougon)',
    location: 'Zone Industrielle Yopougon',
    manager: 'Kouassi Jean-Philippe',
    siteId: 'ALL'
  },
  {
    id: 'MAG-02',
    code: 'MAG-BEN-02',
    name: 'Magasin Bingerville (Chantier)',
    location: 'Chantier Station Bingerville',
    manager: 'Assistant Logistique Bingerville',
    projectId: 'CIV-2026-ASS-BEN-002',
    siteId: 2
  },
  {
    id: 'MAG-03',
    code: 'MAG-SNG-03',
    name: 'Magasin Songon (Chantier)',
    location: 'Chantier Pompage Songon',
    manager: 'Assistant Logistique Songon',
    projectId: 'CIV-2026-ASS-SON-001',
    siteId: 1
  },
  {
    id: 'MAG-04',
    code: 'MAG-DEP-04',
    name: 'Dépôt Chantier Secondaire',
    location: 'Base Vie Chantier',
    manager: 'Magasinier Chantier',
    siteId: 'ALL'
  }
];

export const INITIAL_PURCHASE_REQUESTS: PurchaseRequest[] = [
  {
    id: 'DA-2026-001',
    code: 'DA-2026-001',
    projectId: 'CIV-2026-ST-BING-001',
    projectName: 'Station de Traitement des Boues de Vidange — Commune Bingerville',
    wbsId: 'CIV-2026-ST-BING-001-SEC1-ITEM1',
    wbsCode: '000.1',
    wbsName: 'Installation générale de chantier et des services généraux de l’entreprise',
    nature: 'MAT',
    itemDescription: 'Ciment CPA (Coulage de radier et BP - Approvisionnement 300 sacs)',
    quantity: 300,
    unit: 'Sac',
    estimatedUnitPrice: 4900,
    estimatedTotal: 1470000,
    desiredDate: '2026-08-25',
    urgency: 'Normale',
    justification: 'Coulage radier et voiles du bassin de sédimentation',
    createdBy: 'SEA Alphonse',
    createdAt: '2026-08-17 09:30',
    status: 'BC Généré',
    budgetCheck: {
      budget: 159492422,
      committed: 64962422,
      available: 94530000,
      isOverBudget: false,
      overBudgetAmount: 0,
    },
    approvalChain: [
      { role: 'Conducteur de Travaux', user: 'SEA Alphonse', date: '2026-08-17 10:15', status: 'Approuvé', comment: 'Conforme planning' },
      { role: 'Directeur Projet', user: 'SEA Alphonse', date: '2026-08-17 11:00', status: 'Approuvé', comment: 'Validé' },
    ],
    poNumber: 'BC-GEBAT-2026-042',
  },
  {
    id: 'DA-2026-002',
    code: 'DA-2026-002',
    projectId: 'CIV-2026-ST-SONG-002',
    projectName: 'Station de Traitement des Boues de Vidange — Commune Songon',
    wbsId: 'CIV-2026-ST-SONG-002-SEC1-ITEM1',
    wbsCode: '000.1',
    wbsName: 'Installation de chantier & terrassements généraux Songon',
    nature: 'MAT',
    itemDescription: 'FER 10 (Ferraillage de radier et Voiles - 200 barres)',
    quantity: 200,
    unit: 'BARRE',
    estimatedUnitPrice: 4800,
    estimatedTotal: 960000,
    desiredDate: '2026-08-28',
    urgency: 'Normale',
    justification: 'Ferraillage voiles du bassin anaérobie',
    createdBy: 'Bakary Koné',
    createdAt: '2026-08-18 14:00',
    status: 'En attente validation',
    budgetCheck: {
      budget: 95000000,
      committed: 42000000,
      available: 53000000,
      isOverBudget: false,
      overBudgetAmount: 0,
    },
    approvalChain: [],
  },
];

export const INITIAL_PURCHASE_ORDERS: PurchaseOrder[] = [
  {
    id: 'PO-2026-042',
    code: 'BC-GEBAT-2026-042',
    daId: 'DA-2026-001',
    supplier: 'SOCIMAT CÔTE D’IVOIRE',
    totalAmount: 1440000,
    issueDate: '2026-08-17 14:00',
    status: 'Émis',
    items: [
      {
        description: 'Ciment CPJ 42.5 (Sacs 50kg)',
        quantity: 300,
        unitPrice: 4800,
        receivedQty: 0,
      },
    ],
  },
];

export const INITIAL_RECEIPTS: GoodsReceipt[] = [];

export const INITIAL_STOCK_MOVEMENTS: StockMovement[] = [
  {
    id: 'MVT-2026-001',
    code: 'MVT-ENT-001',
    type: 'Entrée',
    itemId: 'STK-CIM-CPA',
    itemName: 'CIMENT CPA (Coulage de radier et BP)',
    quantity: 800,
    unit: 'SAC',
    unitPrice: 4900,
    totalCost: 3920000,
    warehouse: 'Magasin Bingerville (Chantier)',
    projectId: 'CIV-2026-ASS-BEN-002',
    projectName: 'Station de traitement des boues de vidange de Bingerville',
    wbsCode: '02.02.001',
    activityName: 'Béton armé pour Voiles & Radiers bassins',
    sourceDoc: 'BL-2026-089-SOCIMAC',
    user: 'Kouassi Jean-Philippe',
    date: '2026-08-10',
    notes: 'Livraison initiale 800 sacs Ciment CPA par SOCIMAC'
  },
  {
    id: 'MVT-2026-002',
    code: 'MVT-SRT-002',
    type: 'Sortie',
    itemId: 'STK-CIM-CPA',
    itemName: 'CIMENT CPA (Coulage de radier et BP)',
    quantity: 215,
    unit: 'SAC',
    unitPrice: 4900,
    totalCost: 1053500,
    warehouse: 'Magasin Bingerville (Chantier)',
    projectId: 'CIV-2026-ASS-BEN-002',
    projectName: 'Station de traitement des boues de vidange de Bingerville',
    wbsCode: '02.02.001',
    activityName: 'Coulage Béton de Propreté & Voiles A1',
    sourceDoc: 'BS-2026-042',
    user: 'Kouassi Jean',
    date: '2026-08-14',
    notes: 'Sortie magasin pour coulage voile A1'
  },
  {
    id: 'MVT-2026-003',
    code: 'MVT-ENT-003',
    type: 'Entrée',
    itemId: 'STK-FER-10',
    itemName: 'FER 10 (Ferraillage de radier et Voile)',
    quantity: 1500,
    unit: 'BARRE',
    unitPrice: 4800,
    totalCost: 7200000,
    warehouse: 'Magasin Bingerville (Chantier)',
    projectId: 'CIV-2026-ASS-BEN-002',
    projectName: 'Station de traitement des boues de vidange de Bingerville',
    wbsCode: '02.02.002',
    activityName: 'Armatures Voiles & Radiers',
    sourceDoc: 'BL-2026-092-ACI',
    user: 'Kouassi Jean-Philippe',
    date: '2026-08-12',
    notes: 'Livraison 1500 barres Fer 10 par Aciéries de Côte d’Ivoire'
  },
  {
    id: 'MVT-2026-004',
    code: 'MVT-SRT-004',
    type: 'Sortie',
    itemId: 'STK-FER-10',
    itemName: 'FER 10 (Ferraillage de radier et Voile)',
    quantity: 463,
    unit: 'BARRE',
    unitPrice: 4800,
    totalCost: 2222400,
    warehouse: 'Magasin Bingerville (Chantier)',
    projectId: 'CIV-2026-ASS-BEN-002',
    projectName: 'Station de traitement des boues de vidange de Bingerville',
    wbsCode: '02.02.002',
    activityName: 'Ferraillage des Voiles du Bassin 1',
    sourceDoc: 'BS-2026-048',
    user: 'Kouassi Jean',
    date: '2026-08-16',
    notes: 'Sortie atelier ferraillage pour montage armatures'
  },
  {
    id: 'MVT-2026-005',
    code: 'MVT-ENT-005',
    type: 'Entrée',
    itemId: 'STK-SNG-CIM-CPA',
    itemName: 'CIMENT CPA (Coulage de voiles et radiers)',
    quantity: 600,
    unit: 'SAC',
    unitPrice: 4900,
    totalCost: 2940000,
    warehouse: 'Magasin Songon (Chantier)',
    projectId: 'CIV-2026-ASS-SON-001',
    projectName: 'Station de traitement des boues de vidange (Songon)',
    wbsCode: '03.01.002',
    activityName: 'Coulage Béton de Propreté',
    sourceDoc: 'BL-2026-104-SOCIMAC',
    user: 'Assistant Logistique Songon',
    date: '2026-08-18',
    notes: 'Livraison Ciment CPA pour chantier Songon'
  },
  {
    id: 'MVT-2026-006',
    code: 'MVT-SRT-006',
    type: 'Sortie',
    itemId: 'STK-SNG-CIM-CPA',
    itemName: 'CIMENT CPA (Coulage de voiles et radiers)',
    quantity: 190,
    unit: 'SAC',
    unitPrice: 4900,
    totalCost: 931000,
    warehouse: 'Magasin Songon (Chantier)',
    projectId: 'CIV-2026-ASS-SON-001',
    projectName: 'Station de traitement des boues de vidange (Songon)',
    wbsCode: '03.01.002',
    activityName: 'Coulage Béton de Propreté',
    sourceDoc: 'BS-2026-052',
    user: 'Bakary Koné',
    date: '2026-08-20',
    notes: 'Sortie magasin pour béton de propreté bassin Songon'
  }
];



const REAL_DAILY_REPORTS: DailyReport[] = REAL_EXCEL_PRODUCTION.map((item, idx) => ({
  id: `CR-REAL-${idx + 1}`,
  code: `CR-PROD-${idx + 1}`,
  date: '2026-08-15',
  projectId: item.site === 'BINGERVILLE' ? 'CIV-2026-ST-BING-001' : 'CIV-2026-ST-SONG-002',
  projectName: item.site === 'BINGERVILLE' ? 'Station de Traitement des Boues — Commune Bingerville' : 'Station de Traitement des Boues — Commune Songon',
  wbsId: `WBS-REAL-${idx + 1}`,
  wbsCode: `PRD-${idx + 1}`,
  activityName: `${item.ouvrage} — ${item.designation}`,
  weather: 'Ensoleillé',
  plannedQty: Math.round(item.totalQteProd * 1.05),
  realizedQty: item.totalQteProd,
  unit: item.unit,
  workersCount: 14,
  hoursWorked: 8,
  equipmentCount: 2,
  equipmentHours: 8,
  notes: `Production cumulée mesurée sur le site de ${item.site}.`,
  status: 'Validé',
  createdBy: 'SEA Alphonse',
  productivityRate: item.totalQteProd > 0 ? Number(((item.totalQteProd / (item.totalQteProd * 1.05)) * 100).toFixed(1)) : 95.0
}));

export const INITIAL_DAILY_REPORTS: DailyReport[] = [
  ...REAL_DAILY_REPORTS,
  {
    id: 'CR-2026-08-17-01',
    code: 'CR-2026-08-17-01',
    date: '2026-08-17',
    projectId: 'CIV-2026-ASS-001',
    projectName: 'Construction Station de Traitement Bingerville',
    wbsId: 'WBS-BGV-02.01',
    wbsCode: 'WBS-BGV-02.01',
    activityName: 'Frappage armatures et coulage propreté',
    weather: 'Ensoleillé',
    plannedQty: 45,
    realizedQty: 42,
    unit: 'm3',
    workersCount: 18,
    hoursWorked: 8,
    equipmentCount: 2,
    equipmentHours: 7,
    notes: 'Avancement conforme aux objectifs de la journée.',
    status: 'Validé',
    createdBy: 'Bakary Koné',
    productivityRate: 93.3,
  },
];

export const INITIAL_ALERTS: SystemAlert[] = [
  {
    id: 'ALT-2026-001',
    code: 'ALT-BUD-01',
    category: 'Budget',
    severity: 'Moyenne',
    projectId: 'CIV-2026-ASS-001',
    projectName: 'Construction Station de Traitement Bingerville',
    wbsId: 'WBS-BGV-02.02',
    wbsCode: 'WBS-BGV-02.02',
    title: 'EAC supérieur au Budget Révisé',
    message: 'Le coût à chevauchement EAC prévisionnel dépasse le budget alloué de 2,000,000 XOF.',
    observedValue: '112 000 000 XOF',
    thresholdValue: '110 000 000 XOF',
    assignedToRole: 'Cost Controller',
    createdAt: '2026-08-16 16:00',
    status: 'Actif',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'AUD-001',
    timestamp: '2026-08-15 10:00:00',
    user: 'Yacouba Mohamed',
    role: 'Super Admin',
    action: 'INITIALISATION_SYSTEME',
    module: 'CORE',
    objectRef: 'SYSTEM',
    newValue: 'Initialisation de la base de données GEBAT 360° MVP',
  },
];
