import { User, Role } from '../types';

export const INITIAL_USERS: User[] = [
  {
    id: 'USR-001',
    name: 'Yacouba Mohamed',
    email: 'y.mohamed@gebat-sa.com',
    role: 'Super Admin',
    avatar: 'YM',
    employeeCode: 'EMP-2026-001',
  },
  {
    id: 'USR-002',
    name: 'Kouassi Kouadio',
    email: 'k.kouadio@gebat-sa.com',
    role: 'Direction Générale',
    avatar: 'KK',
    employeeCode: 'EMP-2026-002',
  },
  {
    id: 'USR-003',
    name: 'Amina Diallo',
    email: 'a.diallo@gebat-sa.com',
    role: 'DAF',
    avatar: 'AD',
    employeeCode: 'EMP-2026-003',
  },
  {
    id: 'USR-004',
    name: 'Jean-Marc Traoré',
    email: 'jm.traore@gebat-sa.com',
    role: 'Directeur Technique',
    avatar: 'JT',
    employeeCode: 'EMP-2026-004',
  },
  {
    id: 'USR-005',
    name: 'SEA Alphonse',
    email: 'sea.alphonse@gebat-sa.com',
    role: 'Directeur Projet',
    avatar: 'SA',
    employeeCode: 'EMP-2026-005',
    projectIds: ['CIV-2026-ST-BING-001', 'CIV-2026-ST-SONG-002'],
  },
  {
    id: 'USR-006',
    name: 'Yao N’Guessan',
    email: 'y.nguessan@gebat-sa.com',
    role: 'Conducteur de Travaux',
    avatar: 'YN',
    employeeCode: 'EMP-2026-006',
    projectIds: ['CIV-2026-ASS-001'],
  },
  {
    id: 'USR-007',
    name: 'Bakary Koné',
    email: 'b.kone@gebat-sa.com',
    role: 'Chef de Chantier',
    avatar: 'BK',
    employeeCode: 'EMP-2026-007',
    projectIds: ['CIV-2026-ASS-001'],
  },
  {
    id: 'USR-008',
    name: 'Claire Bamba',
    email: 'c.bamba@gebat-sa.com',
    role: 'Cost Controller',
    avatar: 'CB',
    employeeCode: 'EMP-2026-008',
    projectIds: ['CIV-2026-ASS-001', 'PRJ-SNG-2026'],
  },
  {
    id: 'USR-009',
    name: 'Ibrahim Diarra',
    email: 'i.diarra@gebat-sa.com',
    role: 'Achats',
    avatar: 'ID',
    employeeCode: 'EMP-2026-009',
  },
  {
    id: 'USR-010',
    name: 'Moussa Ouattara',
    email: 'm.ouattara@gebat-sa.com',
    role: 'Magasinier',
    avatar: 'MO',
    employeeCode: 'EMP-2026-010',
    projectIds: ['CIV-2026-ASS-001'],
  },
];

export const PERMISSIONS_MATRIX: Record<Role, {
  canCreateProject: boolean;
  canEditBudget: boolean;
  canApproveBudget: boolean;
  canCreateDA: boolean;
  canApproveDA: boolean;
  canIssuePO: boolean;
  canReceiveGoods: boolean;
  canIssueStock: boolean;
  canCreateDailyReport: boolean;
  canValidateDailyReport: boolean;
  canViewAllProjects: boolean;
}> = {
  'Super Admin': {
    canCreateProject: true,
    canEditBudget: true,
    canApproveBudget: true,
    canCreateDA: true,
    canApproveDA: true,
    canIssuePO: true,
    canReceiveGoods: true,
    canIssueStock: true,
    canCreateDailyReport: true,
    canValidateDailyReport: true,
    canViewAllProjects: true,
  },
  'Direction Générale': {
    canCreateProject: true,
    canEditBudget: false,
    canApproveBudget: true,
    canCreateDA: false,
    canApproveDA: true,
    canIssuePO: false,
    canReceiveGoods: false,
    canIssueStock: false,
    canCreateDailyReport: false,
    canValidateDailyReport: true,
    canViewAllProjects: true,
  },
  'DAF': {
    canCreateProject: false,
    canEditBudget: false,
    canApproveBudget: true,
    canCreateDA: false,
    canApproveDA: true,
    canIssuePO: true,
    canReceiveGoods: false,
    canIssueStock: false,
    canCreateDailyReport: false,
    canValidateDailyReport: false,
    canViewAllProjects: true,
  },
  'Directeur Technique': {
    canCreateProject: true,
    canEditBudget: true,
    canApproveBudget: true,
    canCreateDA: true,
    canApproveDA: true,
    canIssuePO: false,
    canReceiveGoods: false,
    canIssueStock: false,
    canCreateDailyReport: false,
    canValidateDailyReport: true,
    canViewAllProjects: true,
  },
  'Directeur Projet': {
    canCreateProject: true,
    canEditBudget: true,
    canApproveBudget: false,
    canCreateDA: true,
    canApproveDA: true,
    canIssuePO: false,
    canReceiveGoods: false,
    canIssueStock: false,
    canCreateDailyReport: false,
    canValidateDailyReport: true,
    canViewAllProjects: true,
  },
  'Conducteur de Travaux': {
    canCreateProject: false,
    canEditBudget: true,
    canApproveBudget: false,
    canCreateDA: true,
    canApproveDA: true,
    canIssuePO: false,
    canReceiveGoods: true,
    canIssueStock: false,
    canCreateDailyReport: true,
    canValidateDailyReport: true,
    canViewAllProjects: false,
  },
  'Chef de Chantier': {
    canCreateProject: false,
    canEditBudget: false,
    canApproveBudget: false,
    canCreateDA: true,
    canApproveDA: false,
    canIssuePO: false,
    canReceiveGoods: false,
    canIssueStock: false,
    canCreateDailyReport: true,
    canValidateDailyReport: false,
    canViewAllProjects: false,
  },
  'Cost Controller': {
    canCreateProject: false,
    canEditBudget: true,
    canApproveBudget: false,
    canCreateDA: false,
    canApproveDA: true,
    canIssuePO: false,
    canReceiveGoods: false,
    canIssueStock: false,
    canCreateDailyReport: false,
    canValidateDailyReport: false,
    canViewAllProjects: true,
  },
  'Achats': {
    canCreateProject: false,
    canEditBudget: false,
    canApproveBudget: false,
    canCreateDA: true,
    canApproveDA: false,
    canIssuePO: true,
    canReceiveGoods: false,
    canIssueStock: false,
    canCreateDailyReport: false,
    canValidateDailyReport: false,
    canViewAllProjects: true,
  },
  'Magasinier': {
    canCreateProject: false,
    canEditBudget: false,
    canApproveBudget: false,
    canCreateDA: true,
    canApproveDA: false,
    canIssuePO: false,
    canReceiveGoods: true,
    canIssueStock: true,
    canCreateDailyReport: false,
    canValidateDailyReport: false,
    canViewAllProjects: false,
  },
};
